# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance
# with the License. A copy of the License is located at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# or in the 'license' file accompanying this file. This file is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES
# OR CONDITIONS OF ANY KIND, express or implied. See the License for the specific language governing permissions
# and limitations under the License.
"""Default constants for Git Repository Research MCP Server."""

class Constants:
    """Constants used throughout the Git Repository Research MCP Server."""

    # Default directory for storing indices
    DEFAULT_INDEX_DIR = '.git_repo_research'
    
    # Default patterns for file inclusion
    DEFAULT_INCLUDE_PATTERNS = [
        '**/*.md',
        '**/*.py',
        '**/*.js',
        '**/*.ts',
        '**/*.java',
        '**/*.go',
        '**/*.rs',
        '**/*.c',
        '**/*.cpp',
        '**/*.h',
        '**/*.hpp',
        '**/*.cs',
        '**/*.rb',
        '**/*.php',
        '**/*.scala',
        '**/*.swift',
        '**/*.kt',
        '**/*.groovy',
        '**/*.sh',
        '**/*.bash',
        '**/*.ps1',
        '**/*.md',
        '**/*.rst',
        '**/*.txt',
        '**/*.html',
        '**/*.css',
        '**/*.scss',
        '**/*.sass',
        '**/*.less',
        '**/*.json',
        '**/*.yml',
        '**/*.yaml',
        '**/*.xml',
        '**/*.toml',
        '**/*.ini',
        '**/*.cfg',
        '**/*.conf',
        '**/*.properties',
        '**/*.tf',
        '**/*.tfvars',
        '**/*.cdk.ts',
        '**/*.jsx',
        '**/*.tsx',
        '**/*.vue',
        '**/*.sql',
        '**/*.graphql',
        '**/*.proto',
        '**/*.dockerfile',
        'Dockerfile',
        'docker-compose.yml',
        'Makefile',
        'CMakeLists.txt',
        '**/*.gradle',
        'LICENSE',
        'README*',
        'CHANGELOG*',
        'CONTRIBUTING*',
        'CODE_OF_CONDUCT*',
    ]
    
    # Default patterns for file exclusion
    DEFAULT_EXCLUDE_PATTERNS = [
        '**/.git/**',
        '**/.github/**',
        '**/.svn/**',
        '**/.hg/**',
        '**/.bzr/**',
        '**/node_modules/**',
        '**/venv/**',
        '**/.venv/**',
        '**/env/**',
        '**/.env/**',
        '**/__pycache__/**',
        '**/.pytest_cache/**',
        '**/.coverage/**',
        '**/coverage/**',
        '**/dist/**',
        '**/build/**',
        '**/.DS_Store',
        '**/*.pyc',
        '**/*.pyo',
        '**/*.pyd',
        '**/*.so',
        '**/*.dll',
        '**/*.exe',
        '**/*.bin',
        '**/*.obj',
        '**/*.o',
        '**/*.a',
        '**/*.lib',
        '**/*.dylib',
        '**/*.ncb',
        '**/*.sdf',
        '**/*.suo',
        '**/*.pdb',
        '**/*.idb',
        '**/*.jpg',
        '**/*.jpeg',
        '**/*.png',
        '**/*.gif',
        '**/*.svg',
        '**/*.ico',
        '**/*.mp4',
        '**/*.mov',
        '**/*.wmv',
        '**/*.flv',
        '**/*.avi',
        '**/*.mkv',
        '**/*.mp3',
        '**/*.wav',
        '**/*.flac',
        '**/*.zip',
        '**/*.tar.gz',
        '**/*.tar',
        '**/*.rar',
        '**/*.7z',
        '**/*.pdf',
        '**/*.docx',
        '**/*.xlsx',
        '**/*.pptx',
        '**/logs/**',
        '**/log/**',
        '**/.idea/**',
        '**/.vscode/**',
        '**/.classpath',
        '**/.project',
        '**/.settings/**',
        '**/.gradle/**',
        '**/target/**',
    ]
